"""
Art-Net to Philips Hue Entertainment Bridge.

This script is the runtime bridge between Unreal Engine and Philips Hue:

1. Unreal Engine sends DMX values as Art-Net ArtDMX UDP packets.
2. This script listens for those UDP packets on the configured Art-Net port.
3. Each fixture is read as four DMX channels: Dimmer, Red, Green, Blue.
4. The resulting RGB values are forwarded to a Hue Entertainment Area.

Most project-specific changes should happen in config.json:

- hue.ip_address: local IP address of the Philips Hue Bridge.
- hue.username / hue.clientkey: credentials generated from the Hue API.
- hue.rid: Hue Entertainment Area resource id.
- artnet.universe: Art-Net universe sent by Unreal Engine.
- artnet.fixture_count: number of Hue lights/fixtures to update.
- artnet.channels_per_fixture: normally 4 for Dimmer, Red, Green, Blue.
"""

import argparse
import asyncio
import json
import socket
import struct
from pathlib import Path

import requests
import urllib3
from hue_entertainment_pykit import Entertainment, Streaming, create_bridge


urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)


def load_config(path):
    """Load the JSON config file used by both the Hue and Art-Net sides."""
    with Path(path).open("r", encoding="utf-8") as file:
        return json.load(file)


def parse_artdmx_packet(data, universe):
    """
    Return the DMX payload from an ArtDMX packet, or None if it should be ignored.

    Art-Net packets contain several packet types. This bridge only cares about
    ArtDMX packets on the configured universe, because those packets carry the
    DMX channel values generated by Unreal Engine.
    """
    if data[:8] != b"Art-Net\x00":
        return None

    # ArtDMX opcode is 0x5000, encoded little-endian in the Art-Net header.
    opcode = struct.unpack("<H", data[8:10])[0]
    if opcode != 0x5000:
        return None

    # Ignore data from other universes so multiple Art-Net streams can coexist.
    packet_universe = struct.unpack("<H", data[14:16])[0]
    if packet_universe != universe:
        return None

    # DMX payload length is big-endian and begins at byte 16 in ArtDMX packets.
    length = struct.unpack(">H", data[16:18])[0]
    return data[18 : 18 + length]


def get_rgb_from_dmx(dmx, start_address):
    """
    Convert one fixture's DMX channels into an RGB tuple.

    Expected channel order:
    - start_address + 0: dimmer / intensity
    - start_address + 1: red
    - start_address + 2: green
    - start_address + 3: blue

    Hue Entertainment expects RGB color values, so the dimmer channel is applied
    as a multiplier before sending the final color.
    """
    if len(dmx) <= start_address + 3:
        return (0, 0, 0)

    dimmer = dmx[start_address] / 255.0
    red = int(dmx[start_address + 1] * dimmer)
    green = int(dmx[start_address + 2] * dimmer)
    blue = int(dmx[start_address + 3] * dimmer)
    return (red, green, blue)


def create_streaming_session(hue_config):
    """
    Create and configure the Hue Entertainment streaming session.

    The values in hue_config come from config.json. They identify the local Hue
    Bridge, authenticate this script, and select the Entertainment API context.
    """
    bridge = create_bridge(
        identification=hue_config["identification"],
        rid=hue_config["rid"],
        ip_address=hue_config["ip_address"],
        swversion=hue_config["swversion"],
        username=hue_config["username"],
        hue_app_id=hue_config.get("hue_app_id", "unreal-hue-ibl"),
        clientkey=hue_config["clientkey"],
        name=hue_config.get("name", "Hue Bridge"),
    )

    entertainment_service = Entertainment(bridge)
    entertainment_configs = entertainment_service.get_entertainment_configs()

    # This reference bridge uses the first Entertainment Area returned by Hue.
    # If a setup has multiple Entertainment Areas, replace this selection with
    # explicit matching by rid or another known config value.
    entertainment_config = list(entertainment_configs.values())[0]

    streaming = Streaming(
        bridge,
        entertainment_config,
        entertainment_service.get_ent_conf_repo(),
    )
    streaming.set_color_space("rgb")
    return streaming


def print_hue_connection_help(hue_config, exc):
    """Print a short, actionable message when the Hue Bridge cannot be reached."""
    ip_address = hue_config.get("ip_address", "<missing>")

    print("")
    print(f"Could not connect to the Hue Bridge at {ip_address}.")
    print("")
    print("Check these items:")
    print("- The Hue Bridge is powered on and connected to the same router/LAN.")
    print("- bridge/config.json has the current Hue Bridge IP, not the computer IP.")
    print("- The computer is on the same network as the Hue Bridge, not guest Wi-Fi.")
    print("- VPN, campus network isolation, or router client isolation is not blocking LAN access.")
    print("")
    print("Quick checks from PowerShell on this computer:")
    print(f"- Test-NetConnection {ip_address} -Port 443")
    print("- Invoke-RestMethod https://discovery.meethue.com/")
    print("")
    print(f"Original error: {exc}")


async def artnet_listener(streaming, artnet_config):
    """
    Listen for Art-Net packets and forward changed fixture colors to Hue.

    The fixture mapping is intentionally simple: fixture N starts at
    N * channels_per_fixture in the DMX payload. With the default 4-channel
    layout, fixture 1 uses channels 1-4, fixture 2 uses 5-8, and so on.
    """
    host = artnet_config.get("host", "0.0.0.0")
    port = int(artnet_config.get("port", 6454))
    universe = int(artnet_config.get("universe", 1))
    fixture_count = int(artnet_config.get("fixture_count", 11))
    channels_per_fixture = int(artnet_config.get("channels_per_fixture", 4))
    minimum_channels = fixture_count * channels_per_fixture

    loop = asyncio.get_event_loop()
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock.bind((host, port))
    sock.setblocking(False)

    # Cache the last RGB values so unchanged DMX frames do not spam Hue updates.
    last_rgbs = [(0, 0, 0)] * fixture_count

    print(f"Listening for Art-Net on {host}:{port}, universe {universe}")

    while True:
        try:
            data = await loop.sock_recv(sock, 1024)
            dmx = parse_artdmx_packet(data, universe)
            if not dmx or len(dmx) < minimum_channels:
                continue

            updated = False
            for index in range(fixture_count):
                address = index * channels_per_fixture
                rgb = get_rgb_from_dmx(dmx, address)
                if rgb != last_rgbs[index]:
                    last_rgbs[index] = rgb

                    # hue-entertainment-pykit expects (red, green, blue, index).
                    # The index maps to the light order inside the selected
                    # Hue Entertainment Area.
                    streaming.set_input((*rgb, index))
                    print(f"Light {index + 1} updated: {rgb}")
                    updated = True

            if not updated:
                await asyncio.sleep(0.01)

        except Exception as exc:
            print(f"Error: {exc}")

        await asyncio.sleep(0.01)


async def main():
    """Parse command-line arguments, open the Hue stream, and start listening."""
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--config",
        default="config.json",
        help="Path to bridge config JSON.",
    )
    args = parser.parse_args()

    config = load_config(args.config)
    try:
        streaming = create_streaming_session(config["hue"])
    except requests.exceptions.RequestException as exc:
        print_hue_connection_help(config.get("hue", {}), exc)
        raise SystemExit(1) from exc

    print("Connecting to Hue Entertainment Stream")
    streaming.start_stream()
    try:
        await artnet_listener(streaming, config["artnet"])
    finally:
        streaming.stop_stream()


if __name__ == "__main__":
    asyncio.run(main())
